version: '3'

services:
  app:
    build: .
    container_name: dcard_popular_post_notify
    restart: always
    environment:
      DC_DEBUG: $DC_DEBUG
      DC_LESS_LIKE_COUNT: $DC_LESS_LIKE_COUNT
      DC_DCARD_POSTS_URL: $DC_DCARD_POSTS_URL
      DC_DCARD_POST_URL: $DC_DCARD_POST_URL
      DC_TELEGRAM_TOKEN: $DC_TELEGRAM_TOKEN
      DC_TELEGRAM_CHAT_ID: $DC_TELEGRAM_CHAT_ID
      DC_TELEGRAM_DISABLE_WEB_PAGE_PREVIEW: $DC_TELEGRAM_DISABLE_WEB_PAGE_PREVIEW
      DC_TELEGRAM_SEND_MESSAGE_URL: $DC_TELEGRAM_SEND_MESSAGE_URL
      DC_DB_MIGRATE: $DC_DB_MIGRATE
      DC_DB_URL: $DC_DB_URL
